---
- name: Safely patch all worker nodes (no dist-upgrade)
  hosts: workers
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade installed packages only (safe mode)
      apt:
        upgrade: yes

