---
- name: Safely patch all worker nodes
  hosts: workers
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages to latest version (safe mode)
      apt:
        upgrade: dist
